--Explore all objects in the database
USE DataWarehouse
SELECT * FROM INFORMATION_SCHEMA.TABLES

--Explore all columns in the database
SELECT * FROM  INFORMATION_SCHEMA.COLUMNS

--Dimension explorations


--Explore all categories 'The major Divisions"
SELECT DISTINCT category, subcategory, product_name FROM gold.dim_products
ORDER BY 1,2,3

--Explore the date columns; the scope of the data and timespan
 --select the first and the last sales dat
 SElECT 
 MIN(order_date) AS first_order_date,
 MAX(order_date) AS last_order_date
 FROM gold.fact_sales

 --How many years of sales available
 SElECT 
 MIN(order_date) AS first_order_date,
 MAX(order_date) AS last_order_date,
 DATEDIFF (year, MIN(order_date), MAX(order_date)) AS order_range_years
 FROM gold.fact_sales

 --Find the youngest and the oldest customer
 SELECT 
 MIN(birthdate) AS oldest_birthdate,
 DATEDIFF(year, MIN(birthdate), GETDATE()) AS oldest_age,
 MAX(birthdate) AS youngest_birthdate
 FROM gold.dim_customers


 SELECT * FROM gold.dim_products
 SELECT * FROM gold.dim_customers
 SELECT * FROM gold.fact_sales
 --Measure explorations; Big numbers
 --Find the Total sales
 SELECT
 SUM(sales_amount) AS Total_sales
 FROM gold.fact_sales 

 --Find how many items are sold
 SELECT
 SUM(quantity) AS Total_quantity
 FROM gold.fact_sales 

 --Find the average selling price
 SELECT
 AVG(price) AS Average_price
 FROM gold.fact_sales

 --Find the total number of orders
 SELECT
 COUNT( DISTINCT order_number)AS Total_orders
 FROM gold.fact_sales

 --Find the total number of products
 SELECT
 COUNT(DISTINCT product_key)AS Total_products
 FROM gold.dim_products

 --Find the total number of customers
 SELECT
 COUNT(DISTINCT customer_id)AS Total_customers
 FROM gold.dim_customers

 --Find the total number of customers that placed an order
SELECT COUNT(DISTINCT customer_key) AS customers_placed_orders
FROM gold.fact_sales; 


--Generate a report that shows all key metrics of the business
SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity',SUM(quantity) FROM gold.fact_sales 
UNION ALL
SELECT 'Average Price',AVG(price) FROM gold.fact_sales 
UNION ALL
SELECT 'Total Nr. Orders',COUNT(DISTINCT order_number) FROM gold.fact_sales 
UNION ALL
SELECT 'Total Nr. Products',COUNT(product_name) FROM gold.dim_products
UNION ALL
SELECT 'Total Nr. Customers',COUNT(customer_key) FROM gold.dim_customers


--Magnitude analysis
--Find total customers by countries
SELECT 
Country,COUNT(customer_key)AS total_customers
FROM gold.dim_customers
GROUP BY country ORDER BY total_customers DESC

--Find total customers by gender
SELECT 
gender,COUNT(customer_key)AS total_customers
FROM gold.dim_customers
GROUP BY gender ORDER BY total_customers DESC

--Find total products by category
SELECT 
category,COUNT(product_id)AS total_products
FROM gold.dim_products
GROUP BY category ORDER BY total_products DESC

--What is the average costs in each category
SELECT 
category,AVG(cost)AS average_cost
FROM gold.dim_products
GROUP BY category ORDER BY average_cost DESC

--What is the total revenue generated for each category
SELECT
p.category,
SUM(f.sales_amount) AS Total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY category ORDER BY Total_revenue DESC

--Find total revenue is generated by each customer
SELECT 
cu.first_name,
cu.last_name,
SUM(f.sales_amount) as Customer_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers cu
ON cu.customer_key = f.customer_key
GROUP BY cu.first_name,cu.last_name ORDER BY Customer_revenue DESC

--What is the distribution of sold items across countries
SELECT 
c.country,
SUM(f.quantity) as total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY c.country ORDER BY total_sold_items DESC

--Ranking Analysis
--Order the values of our dimensions by measures
--1.Which 5 products genarated the highest revenue
SELECT TOP 5
p.product_name,
SUM(f.sales_amount) AS Total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY product_name ORDER BY Total_revenue DESC


-- 5 worst perfoming products
SELECT TOP 5
p.product_name,
SUM(f.sales_amount) AS Total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY product_name ORDER BY Total_revenue ASC

--Window functions ; Top 5 
SELECT
p.product_name,
SUM(f.sales_amount) Total_revenue,
ROW_NUMBER() OVER (ORDER BY SUM(f.sales_amount) DESC) AS rank_products
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY product_name 

--OR
SELECT *
FROM(
	SELECT
	p.product_name,
	SUM(f.sales_amount) Total_revenue,
	ROW_NUMBER() OVER (ORDER BY SUM(f.sales_amount) DESC) AS rank_products
	FROM gold.fact_sales f
	LEFT JOIN gold.dim_products p
	ON p.product_key = f.product_key
	GROUP BY product_name)t
WHERE rank_products <= 5
